function [fitresult, gof] = createFit_poly4(w_, f_)
%CREATEFIT(W_,F_)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : w_
%      Y Output: f_
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Mar-2016 11:25:45


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( w_, f_, f_ );

% Set up fittype and options.
ft = fittype( 'poly4' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'f_ vs. w_', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'w_' );
% ylabel( 'f_' );
% grid on


