function [fitresult, gof] = createFit_sin4(w_, f_)
%CREATEFIT(W_,F_)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : w_
%      Y Output: f_
%      Weights : f_
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Mar-2016 12:19:54


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( w_, f_, f_ );

% Set up fittype and options.
ft = fittype( 'sin4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [24506.1646397554 0.0189428620782721 -2.84149292999668 6091.39722769615 0.0378857241565442 1.61784451988559 463.09483236214 0.113657172469633 1.62285504370068 1038.14895687624 0.0757714483130883 2.57438955146715];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'f_ vs. w_ with f_', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'w_' );
% ylabel( 'f_' );
% grid on


